<?php

return [
    'names' => [
        'min_length' => 2,
        'max_length' => 60,
        'blocked_phrases' => [
            'john doe',
            'jane doe',
            'test',
            'test user',
            'dummy',
            'sample',
            'unknown',
            'n/a',
            'none',
            'null',
            'admin',
            'support',
            'customer',
            'fixer',
            'user',
            'qwerty',
            'asdf',
        ],
        'blocked_substrings' => [
            'http',
            'www',
            '@',
            '.com',
        ],
    ],

    'emails' => [
        'allowed_domains' => [
            'gmail.com',
            'yahoo.com',
            'yahoo.co.uk',
            'outlook.com',
            'hotmail.com',
            'icloud.com',
            'live.com',
            'msn.com',
            'proton.me',
            'protonmail.com',
            'yahoo.co.za',
            'gmail.co.za',
            'zamtel.zm',
            'mtn.zm',
            'airtel.zm',
        ],
        'blocked_domains' => [
            'example.com',
            'example.org',
            'example.net',
            'localhost',
            'invalid',
            'test.com',
            'mailinator.com',
            'yopmail.com',
            'guerrillamail.com',
            '10minutemail.com',
            'temp-mail.org',
        ],
        'blocked_local_parts_exact' => [
            'example',
            'user',
            'admin',
        ],
        'blocked_local_part_patterns' => [
            '/^(test|demo|fake|admin)\d+$/i',
        ],
    ],
];
