<?php

return [
    'map' => [
        'Central' => [
            'Kabwe',
            'Kapiri Mposhi',
            'Mkushi',
            'Serenje',
            'Mumbwa',
            'Chibombo',
            'Chisamba',
            'Ngabwe',
            'Itezhi-Tezhi (bordering)',
            'Mulungushi',
            'Namalundu',
            'Nansanga Farming Block',
            'Blue Lagoon',
        ],
        'Copperbelt' => [
            'Ndola',
            'Kansenshi',
            'Itawa',
            'Masala',
            'Chifubu',
            'Pamodzi',
            'Ndeke',
            'Chililabombwe',
            'Kakoso',
            'Lubengele',
            'Kasumbalesa',
            'Chingola',
            'Nchanga North',
            'Nchanga South',
            'Kabundi',
            'Chiwempala',
            'Mufulira',
            'Kankoyo',
            'Kantanshi',
            'Buteko',
            'Luanshya',
            'Roan',
            'Mpatamatu',
            'Mikomfwa',
            'Kalulushi',
            'Chambishi',
            'Lufwanyama',
            'Masaiti',
            'Mpongwe',
            'Kitwe',
            'Nkana East',
            'Nkana West',
            'Wusakile',
            'Chimwemwe',
            'Mindolo',
            'Riverside',
            'Parklands',
            'Garneton',
        ],
        'Eastern' => [
            'Chipata',
            'Kalongwezi',
            'Moth',
            'Magazine',
            'Katete',
            'Petauke',
            'Lundazi',
            'Chasefu',
            'Chipangali',
            'Kasenengwa',
            'Lumezi',
            'Mambwe',
            'Nyimba',
            'Sinda',
            'Vubwi',
            'Chadiza',
        ],
        'Luapula' => [
            'Mansa',
            'Samfya',
            'Kawambwa',
            'Nchelenge',
            'Mwense',
            'Chembe',
            'Chienge',
            'Chipili',
            'Milenge',
            'Lunga',
            'Mwansabombwe',
        ],
        'Lusaka' => [
            'Lusaka CBD',
            'Kamwala',
            'Kabwata',
            'Chilenje',
            'Libala',
            'Woodlands',
            'Kabulonga',
            'Rhodes Park',
            'Northmead',
            'Longacres',
            'Chelstone',
            'Avondale',
            'Munali',
            'Olympia',
            'Roma',
            'Ibex Hill',
            'Foxdale',
            'New Kasama',
            'PHI',
            'Kalundu',
            'Bauleni',
            'Kalingalinga',
            'Mtendere',
            'Ng\'ombe',
            'SOS',
            'Matero',
            'Mandevu',
            'George',
            'Chaisa',
            'Garden Compound',
            'Chipata Compound',
            'Kanyama',
            'Misisi',
            'Chibolya',
            'John Laing',
            'John Howard',
            'Jack Compound',
            'Garden House',
            'Zani Muone',
            'Makeni',
            'Chilanga',
            'Linda',
            'Shimabala',
            'Kafue',
            'Shikoswe',
            'Chipapa',
            'Chirundu',
            'Chiawa',
            'Chongwe',
            'Palabana',
            'Silverest',
            'Kasisi',
            'Kanakantapa',
            'Rufunsa',
            'Shikabeta',
            'Luangwa (Feira)',
        ],
        'Muchinga' => [
            'Chinsali',
            'Isoka',
            'Nakonde',
            'Mpika',
            'Mafinga',
            'Shiwang\'andu',
            'Lavushimanda',
            'Chilonga',
            'Kanyelele',
            'Chikwa',
        ],
        'Northern' => [
            'Kasama',
            'Mbala',
            'Mpulungu',
            'Mporokoso',
            'Kaputa',
            'Luwingu',
            'Mungwi',
            'Nsama',
            'Senga Hill',
            'Lunte',
            'Lupososhi',
            'Chilubi',
        ],
        'North-Western' => [
            'Solwezi',
            'Kimasala',
            'Kyawama',
            'Kansanshi',
            'Kalumbila',
            'Mwinilunga',
            'Zambezi',
            'Chavuma',
            'Kabompo',
            'Kasempa',
            'Mufumbwe',
            'Manyinga',
            'Ikelenge',
            'Mushindamo',
        ],
        'Southern' => [
            'Livingstone',
            'Maramba',
            'Dambwa North',
            'Dambwa Central',
            'Libuyu',
            'Choma',
            'Batoka',
            'Mazabuka',
            'Magoye',
            'Monze',
            'Namwala',
            'Kalomo',
            'Zimba',
            'Kazungula',
            'Siavonga',
            'Gwembe',
            'Sinazongwe',
            'Chikankata',
            'Pemba',
            'Itezhi-Tezhi',
            'Siavonga Lake Kariba Shore',
        ],
        'Western' => [
            'Mongu',
            'Lealui',
            'Kaoma',
            'Senanga',
            'Sesheke',
            'Katima Mulilo Border (Zam side)',
            'Shangombo',
            'Sioma',
            'Sikongo',
            'Nalolo',
            'Nkeyema',
            'Luampa',
            'Kalabo',
            'Lukulu',
            'Mitete',
            'Mwandi',
            'Mulobezi',
            'Limulunga',
        ],
    ],
];
